workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/build
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: false
        - pattern: master
          include: true
          source: true
    scripts:
      - flutter packages pub get
    artifacts:
      - flutter_drive.log
    publishing:
      slack:
        channel: "#builds"
        notify_on_build_start: true
