workflows:
  development:
    name: Development
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/build
    triggering:
      events:
        - pull_request
        - tag
      branch_patterns:
        - pattern: master
          include: true
          source: false
    scripts:
      - flutter packages pub get
      - flutter test
