name: Build & test

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.json'
  schedule:
      - cron: "0 5 * * 4"

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: macos-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
    
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', 'beta'
          flutter-version: '2.8.1'
      
      - name: Run Flutter doctor
        run: flutter doctor

      - name: Get flutter dependencies
        run: flutter pub get
      
      #- name: Check for any formatting issues in the code
      #  run: flutter format --set-exit-if-changed .
      
      - name: Statically analyze the Dart code for any errors
        run: flutter analyze .
      
      - name: Run widget tests for our flutter project
        run: flutter test
      
      - name: Build apk 
        run: |
          cd example
          flutter build apk

      - name: Run iOS build
        run: |
          cd example
          flutter build ios --release --no-codesign

      # - name: Upload generated apk to the artifacts
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: release-apk
      #    path: ${{ matrix.project }}/build/app/outputs/apk/release/app-release.apk
